name: "Java"

on:
  push:
    branches:
      - main
    pull_request:
    workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Clone repository"
        uses: actions/checkout@master

      - name: "Build project"
        run: ./gradlew build