name: "Java"

on:
  push:
    branches:
      - master
    pull_request:
    workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
        with:
          java-version: '17'

      - name: "Build project"
        run: ./gradlew build
